add NumberFormat tryParse and test
dart-lang/i18n pull request #633
Opened 2023-04-20 07:30 UTC by utamori

- add tryParse (wrap Parse)
- add tests

related issue https://github.com/dart-lang/i18n/issues/191

origin pr https://github.com/dart-lang/intl/pull/577

2023-04-20 08:31 UTC, mosuem requested changes
Please add a changelog entry

2023-04-20 08:41 UTC, utamori commented
Do I just add it to https://github.com/dart-lang/i18n/blob/main/pkgs/intl/CHANGELOG.md#0181-dev? 
I see that 0.18.1 has already been released.

2023-04-20 08:59 UTC, mosuem commented
Sorry about that, #635 should fix this - please wait until it is merged, or rebase onto that branch.

Thanks for going through the hassle of refiling the PRs!

2023-04-24 07:23 UTC, mosuem commented on pkgs/intl/CHANGELOG.md
> +## 0.19.0-dev
Please also update the pubspec file to match this, see the result of the `Publish` github action workflow.

2023-04-25 08:47 UTC, merged