abstract number parsing
dart-lang/i18n pull request #686
Opened 2023-07-24 04:10 UTC by anqit

This is a step towards allowing all of the incredible number formatting work that has been done in this package to be reused for more general or custom purposes. For example, [this feature request](https://github.com/a14n/dart-decimal/issues/52) could then be fairly trivial to implement. 

---

- [X] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

2023-08-20 00:59 UTC, anqit commented
@mosuem I see you've approved some other PRs, is there any way to get some thoughts on this?

2023-08-21 05:57 UTC, mosuem requested changes

2023-08-21 05:57 UTC, mosuem commented on pkgs/intl/lib/src/intl/number_format.dart
> +  num parse(String text) => parseWith(text, (f, t) => NumberParser(f, t));
Nit: 
```suggestion
  num parse(String text) => parseWith((f, t) => NumberParser(f, t), text);
```

2023-08-21 05:57 UTC, mosuem commented on pkgs/intl/lib/src/intl/number_format.dart
> +  // TODO: use constructor tear-off syntax when dart sdk version >= 2.15
You can also just increase the SDK constraint to allow tear-offs.

2023-08-21 05:57 UTC, mosuem commented on pkgs/intl/lib/src/intl/number_parser.dart
>  ///  A one-time object for parsing a particular numeric string. One-time here
```suggestion
/// A one-time object for parsing a particular numeric string. One-time here
```

2023-08-21 05:57 UTC, mosuem commented
Some small changes, otherwise LGTM! Sorry about the delay.

2023-08-22 14:47 UTC, anqit commented
> Some small changes, otherwise LGTM! Sorry about the delay.

Np, @mosuem, thanks for taking a look. I believe I've addressed your comments.

2023-08-23 08:05 UTC, mosuem commented on pkgs/intl/lib/src/intl/number_format.dart
> +  // TODO: use constructor tear-off syntax when dart sdk version >= 2.15
The sdk constraint is `sdk: ^3.0.0` now anyways, so feel free to remove the todo.

2023-08-23 08:16 UTC, mosuem approved these changes

2023-08-28 00:30 UTC, anqit commented
@mosuem can this be merged?

2023-08-28 08:57 UTC, merged

2023-09-07 17:45 UTC, anqit commented
@mosuem curious what kind of release cadence, if any, this library follows? any idea when a 0.19 release could be expected? thanks!