Support WASM for `package:intl`
dart-lang/i18n pull request #802
Opened 2024-02-17 17:50 UTC by IchordeDionysos

Adds support for compiling to WASM engine.

Fixes #801 

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

2024-02-17 18:17 UTC, kevmoo commented on pkgs/intl/lib/src/http_request_data_reader.dart
> +  Future<String> _getString(String url, Client client) {
while you're here, make this `async` – it'll be easier!

2024-02-17 18:18 UTC, kevmoo requested changes

2024-02-17 18:18 UTC, kevmoo commented on pkgs/intl/pubspec.yaml
> +  http: ^1.0.0
You'll need to bump up the min SDK to 3.3 – also need to add a changelog entry!

2024-02-17 19:08 UTC, IchordeDionysos commented on pkgs/intl/lib/src/http_request_data_reader.dart
> +  Future<String> _getString(String url, Client client) {
Yep changed it :)

2024-02-17 19:10 UTC, IchordeDionysos commented on pkgs/intl/pubspec.yaml
> +  http: ^1.0.0
Added a changelog entry explaining the added dependencies and the support for WASM.

Not 100% sure about the minimum `package:http` version. I tried with `http: 1.0.0`, and the analysis worked for me.
`http` `v1.2.1` requires also Dart `3.3` would still keep it at `http: ^1.0.0` if I should change it as well, let me know.

Wanted to support the most possible versions to make it as compatible as I can with other dependencies.

2024-02-18 06:39 UTC, kevmoo reviewed
You also need to migrate number_format_compact_web_test.dart

2024-02-18 13:47 UTC, IchordeDionysos commented
@kevmoo It's actually quite challenging at least for me, to figure out how this all works :D 

`dart fix` (SDK v3.3.0) did not work and did not suggest anything to me ... 
There seems to be no equivalent to `js.newObject()`. Should I use mocking as described [here](https://dart.dev/interop/js-interop/mock)?

What is especially confusing is that previously it was `js.callMethod(1234, 'toLocalString,' [...args]`, which doesn't translate 1-to-1 to `Number.toLocalString()` on the JS-side.

In Dart, the function was called on the "object"/primitive value, while in JS, it's called on the class.

So I'm kinda stuck ...

2024-02-19 00:14 UTC, kevmoo commented
@srujzs – any ideas?

2024-02-20 00:07 UTC, srujzs commented
Might not have the full context, so feel free to keep asking me questions if my answers are insufficient for the purpose:

> js.newObject()

The replacement for this is just the `JSObject` constructor [here](https://api.dart.dev/dev/3.4.0-131.0.dev/dart-js_interop/JSObject/JSObject.html) (the comment will be a little more clear with another CL cleaning up documentation).

> What is especially confusing is that previously it was js.callMethod(1234, 'toLocalString,' [...args], which doesn't translate 1-to-1 to Number.toLocalString() on the JS-side.

You can write an interop member for `JSNumber` itself so that you can use an instance method on a JS number e.g.

```dart
extension on JSNumber {
  external String toLocaleString([String locale]);
}
...
1234.toJS.toLocaleString();
```

2024-02-21 20:18 UTC, IchordeDionysos commented
@srujzs that was too easy :D

2024-02-21 20:20 UTC, kevmoo commented
For points: test on wasm

```yaml
      - name: Run Chrome tests - wasm
        run: dart test --platform chrome --compiler dart2wasm
        if: always() && steps.install.outcome == 'success' && matrix.sdk == 'dev'
```

2024-02-21 20:45 UTC, srujzs commented on pkgs/intl/test/number_format_compact_web_test.dart
> +  if (notation != null) options.setProperty('notation'.toJS, notation.toJS);
This is totally okay as is, but because you're using `String`s, you can alternative write these `setProperty` calls as `options['notation'] = notation.toJS` for brevity.

2024-02-21 20:54 UTC, IchordeDionysos commented on pkgs/intl/test/number_format_compact_web_test.dart
> +  if (notation != null) options.setProperty('notation'.toJS, notation.toJS);
Uhh nice, didn't know that this is possible as it's not listed here under the operators
![image](https://github.com/dart-lang/i18n/assets/10195482/a6f55b41-6673-4f24-8774-a0adf669f043)

2024-02-21 20:55 UTC, kevmoo commented on .github/workflows/intl.yml
> +        if: always() && steps.install.outcome == 'success' && matrix.sdk == 'dev'
```suggestion
        if: always() && matrix.sdk == 'dev'
```

and drop the `install` ID above.

2024-02-21 20:55 UTC, IchordeDionysos commented on .github/workflows/intl.yml
> +        id: install
```suggestion
```

2024-02-21 21:13 UTC, merged

2024-02-21 22:13 UTC, srujzs commented on pkgs/intl/test/number_format_compact_web_test.dart
> +  if (notation != null) options.setProperty('notation'.toJS, notation.toJS);
These are extension methods in `js_interop_unsafe` instead: https://api.dart.dev/dev/3.4.0-154.0.dev/dart-js_interop_unsafe/JSObjectUnsafeUtilExtension.html, but yeah it's hard to get to that extension in the first place because it's not written here.